version: '3'

services:
  db:
    image: mysql
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=luongtruong
      - MYSQL_DATABASE=database
    ports:
      - '3306:3306'
    expose:
      - '3306'
