version: '3'

services:
  db:
    image: mysql:8.4.2
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=luongtruong
      - MYSQL_DATABASE=database
    ports:
      - '3307:3306'
    expose:
      - '3306'

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage:/data
    environment:
      - MINIO_ROOT_USER=truongluong
      - MINIO_ROOT_PASSWORD=truongluong
    command: server --console-address ":9001" /data
    expose:
      - '9000'
      - '9001'
