export enum EEnv {
  PORT = 'PORT',
  SWAGGER = 'SWAGGER',
  CLIENT_URL = 'CLIENT_URL',
  CRYPTO_SECRET_KEY = 'CRYPTO_SECRET_KEY',
  NORMAL_USER_ROLE_ID = 'NORMAL_USER_ROLE_ID',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',

  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASS = 'EMAIL_PASS',

  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN',

  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN',

  MINIO_ACCESS_KEY = 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY = 'MINIO_SECRET_KEY',
  MINIO_CLIENT_URL = 'MINIO_CLIENT_URL',
  MINIO_REGION = 'MINIO_REGION',
  MINIO_BUCKET = 'MINIO_BUCKET',
}
