export enum EError {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_OR_PASSWORD_INVALID = 'EMAIL_OR_PASSWORD_INVALID',
  USER_EXIST_WITH_EMAIL = 'USER_EXIST_WITH_EMAIL',
  VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED',
  INVALID_OTP_TYPE = 'INVALID_OTP_TYPE',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  TAG_EXIST_WITH_NAME = 'TAG_EXIST_WITH_NAME',
}
